// Generated by gencpp from file ros_term/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_TERM_MESSAGE_ADDTWOINTS_H
#define ROS_TERM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_term/AddTwoIntsRequest.h>
#include <ros_term/AddTwoIntsResponse.h>


namespace ros_term
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_term


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_term::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_term::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_term::AddTwoInts > {
  static const char* value()
  {
    return "ros_term/AddTwoInts";
  }

  static const char* value(const ::ros_term::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_term::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_term::AddTwoInts >
template<>
struct MD5Sum< ::ros_term::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_term::AddTwoInts >::value();
  }
  static const char* value(const ::ros_term::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_term::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_term::AddTwoInts >
template<>
struct DataType< ::ros_term::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_term::AddTwoInts >::value();
  }
  static const char* value(const ::ros_term::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_term::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_term::AddTwoInts >
template<>
struct MD5Sum< ::ros_term::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_term::AddTwoInts >::value();
  }
  static const char* value(const ::ros_term::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_term::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_term::AddTwoInts >
template<>
struct DataType< ::ros_term::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_term::AddTwoInts >::value();
  }
  static const char* value(const ::ros_term::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TERM_MESSAGE_ADDTWOINTS_H
